### ISSUE TITLE
In the section 4.2.1 of the paper . it requires the W in the bottom is different from each other according to the Eq.(4),but the code in the model doesn't do like that

### ISSUE THREAD

**Issue by zhaopanpan73** [xuehy/Cross-View-Gait-Deep-CNNs#1]
In section 4.2.1 ." where Wl denotes the weights on the lth layer (or ﬁlters for convolution layers), and f is a non-linear activation function. Note that the bias terms, the spatial pooling and crossmap normalization operations are omitted here for clarity, and **that W1 and W1` are different from each other**."

**Comment by zhaopanpan73** [comment]
I wonder if I understand the wrong way

**Comment by xuehy** [comment]
I find the descriptions in the paper also confusing compared with the model in Figure 4. Maybe I am wrong. I'll try your understanding of the model in the next two days.

**Comment by zhaopanpan73** [comment]
thank you for your instant reply.I  will wait .

**Comment by zhaopanpan73** [comment]
Thank you for your timely reply.I will wait in hope!

**Comment by zhaopanpan73** [comment]
another Problem 。mabe missing the "DatasetForTest methold " in the dataset.py

**Comment by xuehy** [comment]
The model is added, and the results are close to before.

**Comment by zhaopanpan73** [comment]
thank you! and  I am  wondering the configuration of your server to run the code.and How long does it take to run?

**Comment by xuehy** [comment]
GTX 1080 Ti. Around 10 hours.

**Comment by zhaopanpan73** [comment]
Great! wish you have a nice day!
