### ISSUE TITLE
Outofmemory

### ISSUE THREAD

**Issue by Fly2flies** [xuehy/Cross-View-Gait-Deep-CNNs#3]
Hello,
 I want to train this network in my laptop. However, apparently memory is not enough.So,can you give some advice about how to change the data batch size for each training.That's to say, how do you adjust the iteration variable in train.py to ensure that the program is still running correctly ?
 Thanks a lot. Because I've just been exposed to this knowledge

**Comment by xuehy** [comment]
In train.py, line 29, ```bs``` is batch size.

**Comment by Fly2flies** [comment]
It shows that :RuntimeError: CUDA error: no error     
                     fatal : Memory allocation failure
Whether I should reduce the  iterations a little bit or not?

**Comment by xuehy** [comment]
What is your batch size? How large is your GPU memory?
