### ISSUE TITLE
The test accuracy and time cost

### ISSUE THREAD

**Issue by wwyfzu502** [xuehy/Cross-View-Gait-Deep-CNNs#6]
Thank you very much for sharing! 
I still have  some doubts. The first one is about the result table you offered in read me. It seems that there is a gap between your result and the paper's(showed below)
![image](https://user-images.githubusercontent.com/46233690/50532639-0d9d8c80-0b57-11e9-82a2-a57db9b84f09.png)
Is it the best result you got? How many iterations did it take？

And in your answer for another issue,i notice that you said you spend around 10 hours in GTX 1080 Ti(the same to mine). Did you mean you take 2000K(stop num in your code) iterations in around 10 hours? It seems that 6 days will be spend in my device.

**Comment by wwyfzu502** [comment]
I made a mistake, 3 days will be spend in my device.
I would be very grateful if you could answer my doubts.

**Comment by xuehy** [comment]
I did not try to replicate the results in the paper.  To improve the results, you may need to tune the parameters and wait for the model to converge. Besides, my evaluation method may be different from the original paper's evaluation approach. I think you may check if the evaluations are the same.

**Comment by wwyfzu502** [comment]
All right, I get it. Thank you very much
