### ISSUE TITLE
Does the training code take silhouette or GEI as input

### ISSUE THREAD

**Issue by insidedctm** [xuehy/Cross-View-Gait-Deep-CNNs#8]
The 'Training' section says:

> To train the model, put the CASIA-B dataset silhoutte data under repository

Do you mean the Gait Energy Images derived from the silhouettes? I don't see any code that calculates GEIs.

**Comment by xuehy** [comment]
It is the Gait Energy Image. The dataset contains the GEIs which can be downloaded via the [link](https://kylezheng.org/research-projects/gait-recognition/
).

**Comment by insidedctm** [comment]
Great - thanks for confirming.
